### ISSUE TITLE
Wonderful work!But can't use on 4.5.6.

### ISSUE THREAD

**Issue by tony1016** [OtherDevOpsGene/zap-sonar-plugin#1]
Would u mind downgrade to compatible with  4.5.6?

**Comment by davewichers** [comment]
To be clear Tony, 4.5.6 of what? SonarQube I assume.

**Comment by stevespringett** [comment]
It's already documented in the readme that SonarQube 5.1 or higher is required. At this time, SonarQube 5.4 is the current version. There are no plans on backporting to 4.5.6.
