### ISSUE TITLE
Coveros to help with maintenance

### ISSUE THREAD

**Issue by OtherDevOpsGene** [OtherDevOpsGene/zap-sonar-plugin#11]
Coveros is willing to help or take over the maintenance of this plugin.

One of my team members and I have each written SonarQube plugins before. We are heavy SonarQube and OWASP ZAP users throughout the company. We use both tools in our day-to-day jobs, in our training courses, and often blog and speak about them at conferences.

Please let me know how you would like us to help.

**Comment by stevespringett** [comment]
@gotimer as of now, I do not have any plans on enhancing the plugin further. I simply do not have the time nor am I heavily involved with the ZAP community to know what enhancements the plugin (or zap) could benefit from. The plugin was written at the request of @davewichers back in 2015 and I had some extra bandwidth at the time. But it was never my intention to be the ongoing maintainer.

To my knowledge, the one area of focus the plugin may need is to validate the API changes between SQ5 and SQ6. A community member added SQ6 compatibility with #9 but I have not tested it. I'm thinking the plugin may need some minor cleanup and validation of #9 prior to a binary release.

There isn't a lot of activity with the plugin to date - I'm counting only 11 forks. If @Coveros is willing to accept a transfer to https://github.com/Coveros then I would be willing to do that. It would not affect a large number of people.

Let me know your thoughts.

**Comment by OtherDevOpsGene** [comment]
If you can start the transfer to https://github.com/Coveros, I'll accept it and make the changes in the POM to set it up for our account, emails, TravisCI, etc. over the next week and start some testing.

**Comment by davewichers** [comment]
Steve implemented this as a favor to me. If someone like Gene is willing to
pick it up and continue to maintain it, wherever they want, that's totally
fine with me.

Thanks Steve for building this, and Gene for volunteering to maintain it
going forward.

Thanks, Dave

**Comment by OtherDevOpsGene** [comment]
@stevespringett Can you initiate the transfer to https://github.com/Coveros?

**Comment by stevespringett** [comment]
Can you grant temporary permission to create repos so I can make the transfer? I attempted the transfer and received the following error:
![screen shot 2017-12-21 at 10 05 23 am](https://user-images.githubusercontent.com/3878933/34263923-ba8320f0-e636-11e7-8a2f-26c3b9f656f8.png)

**Comment by OtherDevOpsGene** [comment]
Can we do it in two steps? You transfer to https://github.com/gotimer and I'll transfer to Coveros?

**Comment by stevespringett** [comment]
Yes, that seems reasonable and mitigates risk on Coveros end.

**Comment by OtherDevOpsGene** [comment]
Transferred to https://github.com/Coveros/zap-sonar-plugin successfully. Thanks @stevespringett
