### ISSUE TITLE
JAR for releases

### ISSUE THREAD

**Issue by injcristianrojas** [OtherDevOpsGene/zap-sonar-plugin#19]
We could use the JARs in releases...

**Comment by OtherDevOpsGene** [comment]
I'm not clear on what you are requesting. 

`zap-sonar-plugin.jar` is hosted on the Central Repository. For Maven,
```
<dependency>
    <groupId>org.sonarsource.owasp</groupId>
    <artifactId>sonar-zap-plugin</artifactId>
    <version>1.0.1</version>
</dependency>
```

Is that what you are looking for?

**Comment by injcristianrojas** [comment]
Not really. See here: https://github.com/stevespringett/dependency-check-sonar-plugin/releases

Each release has assets attached to it: ZIP, Tarballs and JARs.

**Comment by OtherDevOpsGene** [comment]
I see. We'll consider it. We are currently publishing our official releases on the Central Repository.

**Comment by OtherDevOpsGene** [comment]
Looks like it worked. Closing
