### ISSUE TITLE
Can't see ZAP report in Sonar

### ISSUE THREAD

**Issue by diegochavezcarro** [OtherDevOpsGene/zap-sonar-plugin#24]
I run sonnar scan (previously tried with Jenkins ZAP Plugin, now with Sonnar Scan Command Line to be sure) and I can't see ZAP report (such as the More->OWASP Dependency Check in the case of that plugin).
Neither can see vulnerabilities in the project.
Versions:
sonar-zap-plugin-1.0.1.jar
Sonarqube Version 6.7.3 (build 38370
SonarQube Scanner 3.1.0.1141
sonnar.properties:
```
sonar.projectKey=jenkinsprueba
sonar.zaproxy.reportPath=reports/JENKINS_ZAP_VULNERABILITY_REPORT.xml
sonar.zaproxy.htmlReportPath=reports/JENKINS_ZAP_VULNERABILITY_REPORT.html
sonar.sources=reports
sonar.zaproxy.report.dir=reports
```
This is the console output:
`C:\Users\dchavez\.jenkins\workspace\ZAPJenkins>sonar-scanner
INFO: Scanner configuration file: C:\tools\sonar-scanner-3.1.0.1141-windows\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: C:\Users\dchavez\.jenkins\workspace\ZAPJenkins\sonar-project.properties
INFO: SonarQube Scanner 3.1.0.1141
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Users\dchavez\.sonar\cache
INFO: SonarQube server 6.7.3
INFO: Default locale: "en_US", source code encoding: "windows-1252" (analysis is platform dependent)
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=85ms
INFO: Server id: AWMXVidGOWZ1uA9DPlu0
INFO: User cache: C:\Users\dchavez\.sonar\cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=62ms
INFO: Download sonar-zap-plugin-1.0.1.jar
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=125ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=48ms
INFO: Load active rules
INFO: Load active rules (done) | time=1259ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=47ms
WARN: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
INFO: Project key: jenkinsprueba
INFO: -------------  Scan jenkinsprueba
INFO: Base dir: C:\Users\dchavez\.jenkins\workspace\ZAPJenkins
INFO: Working dir: C:\Users\dchavez\.jenkins\workspace\ZAPJenkins\.scannerwork
INFO: Source paths: reports
INFO: Source encoding: windows-1252, default locale: en_US
INFO: Load server rules
INFO: Load server rules (done) | time=525ms
INFO: Index files
INFO: 2 files indexed
INFO: Quality profile for web: Sonar way
INFO: Quality profile for xml: Sonar way
INFO: Sensor OWASP Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.xml
INFO: Process Dependency-Check report (done) | time=16ms
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.html
INFO: Sensor OWASP Dependency-Check [dependencycheck] (done) | time=16ms
INFO: Sensor OWASP Zap-Check [zap]
INFO: Process ZAP report
INFO: Process ZAP report (done) | time=78ms
INFO: Sensor OWASP Zap-Check [zap] (done) | time=93ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: 1 source files to be analyzed
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=100ms
INFO: 1/1 source files have been analyzed
INFO: Sensor Web [web]
INFO: Sensor Web [web] (done) | time=612ms
INFO: Sensor XML Sensor [xml]
INFO: Sensor XML Sensor [xml] (done) | time=161ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=4ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=12ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Calculating CPD for 1 file
INFO: CPD calculation finished
INFO: Analysis report generated in 110ms, dir size=93 KB
INFO: Analysis reports compressed in 31ms, zip size=27 KB
INFO: Analysis report uploaded in 62ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/jenkinsprueba
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AWNAjYxf9IwjzzrjNrMb
INFO: Task total time: 5.924 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 8.957s
INFO: Final Memory: 19M/372M
INFO: ------------------------------------------------------------------------`

**Comment by gotimer** [comment]
`WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.xml`

It looks like the WORKSPACE variable isn't being expanded. Try with the expanded path (e.g., `C:\Users\dchavez\.jenkins\workspace`) and see if that makes the report show up. You might need to double up the backslashes for escaping (i.e., `C:\\Users\\dchavez\\.jenkins\\workspace`).

**Comment by diegochavezcarro** [comment]
I don' have a dependency check report, so I think the warning about it does not matter. My issue is with ZAP report.

**Comment by OtherDevOpsGene** [comment]
Try with an absolute path. 

`sonar.zaproxy.reportPath=${WORKSPACE}/zaproxy-report.xml`

It could be that the relative path isn't working.

**Comment by msj1130** [comment]
I got the results view like http://localhost:9000/project/issues?id=org.sonarsource.owasp%3Asonar-zap-plugin&resolved=false&tags=zaproxy. But not table of the result data.
How can i make widget like the Screenshot in sonarqube project dashboard?
Is it possible?
![zap_screenshot](https://user-images.githubusercontent.com/22928699/54009520-7421d500-41ae-11e9-9ef8-b9f230519ce6.JPG)

**Comment by priyankaraghavan** [comment]
I have the following error from log 09:29:07.363 INFO: Process ZAP report

09:29:07.363 WARN: ZAP report does not exist. SKIPPING. Please check property sonar.zaproxy.reportPath: /Users/maersk_mtc03/jenkins_home/workspace/samplepython/report/JENKINS_ZAP_VULNERABILITY_REPORT.xml

But with me as you can see I gave an absolute path still it cannot be seen. I have double checked path and it exists

**Comment by dantemorius** [comment]
I have a similar problem, but even setting the absolute path, the report is not found:

OWASP ZAP Scan Step:
sh 'docker run --rm -v ${WORKSPACE}/zap/:/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t ${URL} -n ${JSON_FILE} -a -d -f openapi -x zaproxy-report.zap -r zaproxy-report.html -J zaproxy-report.json -I'

Archive Artifacts steps:
archiveArtifacts '${WORKSPACE}/zaproxy-report.zap' (or .xml)


SONAR SCAN Step:
sh 'docker run -v $(pwd):/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn -s /usr/src/mymaven/settings.xml -DskipTests clean -f /usr/src/mymaven/$API-api/pom.xml package sonar:sonar -Dsonar.projectKey="${SONAR_NAME}-DAST" -Dsonar.projectName="${SONAR_NAME}-DAST" -Dsonar.zaproxy.reportPath="${WORKSPACE}/zaproxy-report.zap" -Dsonar.language=ZAP -Dsonar.lang.patterns.zap=**/*.zap -Dsonar.dependencyCheck.skip=true'

I have a first Quality Gate integrated with dependency-check at the same Pipeline, but this second don't find the report.I tried almost all possibilities of folders =/

I also tried with xml format in all steps, so i tried to set a custom extention because i saw it working in another pipeline.

When i check the workspace (or set a sh 'ls -lah') the report is there.

Any idea, plz?

**Comment by OtherDevOpsGene** [comment]
Fixed in release 2.1.0

**Comment by sandaliqbal1** [comment]
Does this plugin work with sonar version 8.x ?

**Comment by pethers** [comment]
Using latest version using 8.6 at https://www.hack23.com/sonar/project/extension/zap/report_page?id=com.hack23.cia%3Acia-all&qualifier=TRK , so works well

**Comment by sandaliqbal1** [comment]
kool. Can you tell me how to push the report to sonar? I have sonar plugin in my build.gradle
plugins {
	id 'org.sonarqube' version '2.8'
}
and I'm using following command
./gradlew sonarqube  -Dsonar.zaproxy.htmlReportPath=${WORKSPACE}/report.html
but I dont see the report. My plugin version is 2.0.2.

**Comment by pethers** [comment]
Using plugin version 2.2.0, but think at least 2.1.0 is required https://github.com/OtherDevOpsGene/zap-sonar-plugin/releases/tag/sonar-zap-plugin-2.1.0 since it's added report back support to 8.x sonarqube.

**Comment by OtherDevOpsGene** [comment]
That is correct. 2.1.0 added the report capability, and 2.2.0 is current as of yesterday.

**Comment by raph007** [comment]
I'm running scan via Bamboo plugin (it runs sonnar scanner) and got this in "sonar-project.properties":

```
sonar.zaproxy.reportPath=./security_tests/output/security_scan_api.xml
sonar.zaproxy.htmlReportPath=./security_tests/output/security_scan_api.html
```

but no HTML report in Sonar:

![image](https://user-images.githubusercontent.com/755617/116206054-b156d180-a73e-11eb-811d-dd17a566b4b0.png)

Any ideas how to debug this (Sonar 8.5.1)? I tried absolute paths with no luck.
