### ISSUE TITLE
Enhancement : Publish plugin to sonar plugin page

### ISSUE THREAD

**Issue by lcotonea** [OtherDevOpsGene/zap-sonar-plugin#3]
Hi,

This plugin seems good! Congratulation for the initiative.
However, could you officially publish it to the sonar plugin homepage? 

Thanks!

**Comment by stevespringett** [comment]
Requested the plugin be listed on the 'Other Plugins' page on the SonarQube wiki

https://groups.google.com/forum/#!topic/sonarqube/Ethr5fOeTCw
