### ISSUE TITLE
Error during SonarQube Scanner execution Caused by: The rule 'ZAProxy:10049' does not exist.

### ISSUE THREAD

**Issue by rajendrapenumalli** [OtherDevOpsGene/zap-sonar-plugin#42]
Trying to integrate ZAPProxy results with sonarqube  Coveros plugin but it is giving error as The rule 'ZAProxy:10049' does not exist.

Using ZAP 2.8.0
SonarQube Server: 6.7.6 community edition
SonarQube Plugiin Version: "org.sonarqube" version "2.5

Could you please fix this.

Thanks,
Rajendra

**Comment by OtherDevOpsGene** [comment]
Looks like this was fixed in #64. Release expected later today.

**Comment by OtherDevOpsGene** [comment]
https://github.com/OtherDevOpsGene/zap-sonar-plugin/releases/tag/sonar-zap-plugin-2.2.0
