### ISSUE TITLE
the plugin doesn't support multibranch 

### ISSUE THREAD

**Issue by wingkwong** [OtherDevOpsGene/zap-sonar-plugin#78]
The report fails to be displayed if ``sonar.branch.name`` is defined. 

Should have included "branch" option in

https://github.com/OtherDevOpsGene/zap-sonar-plugin/blob/main/src/main/js/report_page/components/ZapReportApp.js#L7

Ref:

https://sonarcloud.io/web_api/api/measures/component

**Comment by petrjurasek** [comment]
As the fix seems to be merged - is it possible to release new fix version?

Its only change https://github.com/OtherDevOpsGene/zap-sonar-plugin/compare/sonar-zap-plugin-2.2.0...main

2.2.1 version maybe?

**Comment by OtherDevOpsGene** [comment]
Released 2.3.0. Sorry for the delays
