### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by pms1969** [OtherDevOpsGene/zap-sonar-plugin#8]
It would be handy and very nice to have a release on the release page that provided a binary (.jar) for download and installation.  Especially useful for docker installations.

Cheers.
Paul

**Comment by OtherDevOpsGene** [comment]
org.sonarsource.owasp:sonar-zap-plugin:1.0.1 published to Central Repository.

https://oss.sonatype.org/service/local/repositories/releases/content/org/sonarsource/owasp/sonar-zap-plugin/1.0.1/sonar-zap-plugin-1.0.1.jar

**Comment by pms1969** [comment]
Super handy, thank you.
