### ISSUE TITLE
HTML report does not show on SonarQube

### ISSUE THREAD

**Issue by fhperuchi** [OtherDevOpsGene/zap-sonar-plugin#93]
Hi!

I'm generating a full scan ZAP HTML report with this: https://www.zaproxy.org/docs/docker/full-scan/
The HTML file is being generated well. I've checked it.

I'm passing these parameters as recommended [here](https://github.com/OtherDevOpsGene/zap-sonar-plugin#plugin-configuration) to SonarScanner tool:

`/home/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar/bin/sonar-scanner -Dsonar.projectKey=*** -Dsonar.projectName=****  -Dsonar.branch.name=feature/14766-run-automated-pentest-scan -Dsonar.zaproxy.reportPath=tmp/zaproxy-report.xml -Dsonar.zaproxy.htmlReportPath=tmp/zaproxy-report.html `

But the HTML does not show here:

![image](https://user-images.githubusercontent.com/4641123/121690150-da87b300-ca9b-11eb-96be-fdb21bacec82.png)

PS: XML report file (`tmp/zaproxy-report.xml`) is being processed without any issues.

Could you help me?

**Comment by wingkwong** [comment]
@fhperuchi The latest released version doesn't include the fix I made. You may clone the master branch and build the jar.

**Comment by fhperuchi** [comment]
> @fhperuchi The latest released version doesn't include the fix I made. You may clone the master branch and build the jar.

Thanks @wingkwong . I'll try.

**Comment by fhperuchi** [comment]
It worked. Thanks.
